### ISSUE TITLE
Release crates.io by GitHub Action

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/sqlness#14]
### Describe This Problem

When make a new release, there are severals things need to be done:
1. Bump version in Cargo.toml
2. Push new tag
3. Make new release

It would be great to automate this process.

### Proposal

Use GitHub Actions to make new release
- https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1

We can trigger this action when new tags pushed.

**Comment by waynexia** [comment]
I find this repo can generate a beautiful changelog based on the conventional commit message we wrote.
