### ISSUE TITLE
Add default database implementation

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/sqlness#15]
### Describe This Problem

Target of Sqlness is to ensure SQL's correction of one database, so if a database want to use sqlness, it need to implement `Database` trait, although this works as expected, this seems a tedious work.

In SQL world, there are only a few wire protocols, such as MySQL or PostgreSQL. If we can supply a default database with MySQL protocols, then any MySQL-compatible databases can use sqlness with less work.

### Proposal

Add one default database implementation: MySQL

**Comment by dust1** [comment]
Does the default `Database` implementation mean that a mysql service needs to be run when `Database::default()` is executed?

**Comment by waynexia** [comment]
Not like that. From the sqlness side, providing a default database is more like to integrating some mysql-client library, handling the query submission, and result display for users. By doing this, we can make it easier to get started with sqlness, user only needs to handle the start/stop of their services.

**Comment by dust1** [comment]
I see. this issue can be assigned to me.😀

**Comment by waynexia** [comment]
Thanks for taking this! One thing I'm not clear is what SQL client library we will support? I'm not familiar with the ecosystem, does @jiacai2050 have any ideas? 

By the way, I'd prefer to implement this feature as "optional". I.e., users of sqlness can opt-out this built-in default support by feature gate if they don't want to use it.

**Comment by dust1** [comment]
Perhaps to quickly support other databases that have the Mysql protocol?

**Comment by waynexia** [comment]
> Perhaps to quickly support other databases that have the Mysql protocol?

MySQL is a good choice, but there are many MySQL client implementations in Rust. I've not done a comparison between them.

**Comment by jiacai2050** [comment]
https://crates.io/crates/mysql is a popular crates, so we can go with it first.

We can add a feature gate to enable this feature.

> By doing this, we can make it easier to get started with sqlness, user only needs to handle the start/stop of their services.

I think we can go further, we can provide a cli for this default server, and let user start/stop service all by themselves, users can execute this cli against their servers directly, something like

```
sqlness-cli -t mysql -h localhost -p 3306 --case-dir some-directory
```

We can implement this in two steps, first to add default database implementation, then to add this cli.

**Comment by jiacai2050** [comment]
@dust1 Any progress on this? I plan to make a release by next Friday for #25.

Don't take this as push, I can release without this feature. 😃

**Comment by dust1** [comment]
I'm sorry that this issue has not started due to my work. I will try to finish it before next Friday😥
