### ISSUE TITLE
Remove tokio dependency

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/sqlness#20]
### Describe This Problem

In current implementation, sqlness use tokio to do file IO, which is not a requirement, and this cause sqlness to depend on a heavy dependency.

### Proposal

Use std to do file IO, and remove hard requirement of tokio.

**Comment by waynexia** [comment]
Or can we only opt-in `fs` module of tokio, rather than `full` used currently?

**Comment by jiacai2050** [comment]
I can't think of any advantages to leverage tokio to do file IO, and it's a heavy dependency, so I prefer to remove it completely.
