### ISSUE TITLE
Ignore Cargo.lock file

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/sqlness#28]
### Describe this problem

For libraries, cargo.lock shouldn't be checked in git.

### Steps to reproduce

Not required

### Additional Information

https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

**Comment by waynexia** [comment]
Sounds reasonable 👍

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by waynexia** [comment]
If you wish
