### ISSUE TITLE
Support PostgreSQL wire protocol

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/sqlness#44]
### Describe This Problem

MySQL support is already fixed in #26, it would be great if PostgreSQL is also supported.

### Proposal

Implement database trait for PostgreSQL
- https://docs.rs/postgres/latest/postgres/struct.Client.html

**Comment by Lilit0x** [comment]
Hi @jiacai2050 , I am really interested in working on this feature. We could use this [crate](https://github.com/sunng87/pgwire) to achieve that or I am open to any other suggestions. I have worked with and used it for some other project, so I am quite familiar with it.
Thanks

**Comment by jiacai2050** [comment]
Thanks, assigned.

As an reminder, this issue depend on PG client, not server.
