### ISSUE TITLE
InterceptorFactory try_new should return Result

### ISSUE THREAD

**Issue by jiacai2050** [CeresDB/sqlness#60]
Why this method return Optione before? it seems Result is more reasonable, otherwise we cannot know why an interceptor isn't working as expected.

Maybe we can file an issue first.

_Originally posted by @jiacai2050 in https://github.com/CeresDB/sqlness/pull/58#discussion_r1250541187_

**Comment by waynexia** [comment]
This method will be called every time for every registered factory. Thus returning `None` means the text is not applicable to this factory. Maybe we can use `Option<Result<T>>` instead?

**Comment by jiacai2050** [comment]
`Option<Result<T>>` sounds better, but this sounds counterintuitive
> This method will be called every time for every registered factory. 

https://github.com/CeresDB/sqlness/blob/fef48d1c7d177f0c779ad9a08ac7b2423555aac9/sqlness/src/case.rs#L116

A proper solution I think of it's for each interceptor to registered into a registry, then the registry decide which interceptor to build based on context.


```rs
// setup
let registry = InterceptorRegistry.new()
  .add(prefix1, factory1)
  .add(prefix2, factory2)

// usage
interceptor = registry.build_intercetpor(prefix_from_context);
```

Any thoughts?

**Comment by waynexia** [comment]
Sounds good 👍 This is better and clearer
