### ISSUE TITLE
bug: split sql wrongly like `INSERT INTO timestamp VALUES ('1900-1-1 00;00;00');`

### ISSUE THREAD

**Issue by discord9** [CeresDB/sqlness#68]
### Describe this problem

Current version of sqlness parse sql wrongly and will split this sql into three separate ones:
```sql
INSERT INTO timestamp VALUES ('1900-1-1 00;00;00');
```
This is due to this place simply split sql by `;` instead of checking it semantic meaning:
https://github.com/CeresDB/sqlness/blob/5469532cdaf87791b3af5d7e2918e92725f8dfc5/sqlness/src/case.rs#L157
```rs
// An intercetor may generate multiple SQLs, so we need to split them.
        for sql in sql.split(QUERY_DELIMITER) {
```

### Steps to reproduce

```sql
CREATE TABLE timestamp(t TIMESTAMP time index);

INSERT INTO timestamp VALUES ('1900-1-1 00;00;00');
```
will make sqlness think the last sql is three sql:
```sql
INSERT INTO timestamp VALUES ('1900-1-1 00;
00;
00');
```

### Expected behavior

not splitting sql

**Comment by waynexia** [comment]
Looks like this regression was introduced in https://github.com/CeresDB/sqlness/pull/63 cc @jiacai2050 

We need to make a new release after this is fixed. Maybe `0.6.1`? If we don't class #67 as a breaking change.

**Comment by jiacai2050** [comment]
Why you use `;` in time string, shouldn't it be `:`?

**Comment by discord9** [comment]
> Why you use `;` in time string, shouldn't it be `:`?

It's a test for parsing incorrect timestamp, so many corner cases for handling timestamp are covered

**Comment by jiacai2050** [comment]
Got it.

I already submit a PR fix this, will make a release today.

**Comment by jiacai2050** [comment]
Here it is.
- https://github.com/CeresDB/sqlness/releases/tag/v0.6.1
- https://crates.io/crates/sqlness/0.6.1

**Comment by waynexia** [comment]
Thank you @jiacai2050 👍
